# Generated by Django 3.2.9 on 2022-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_places_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contactus',
        ),
    ]
